### ISSUE TITLE
Can't store arbitrary data in World

### ISSUE THREAD

**Issue by bgrosse-midokura** [bbqsrc/cucumber-rust#97] opened 2020-12-28 14:33 UTC
With `0.6.0`, as it wasn't async, I could just put anything in my `World` to keep state across steps.

With `0.7.0` and the async stuff, I can't put something that doesn't implement `UnwindSafe` in my `World`:

```
the type `(...)` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   | pub trait World: Sized + UnwindSafe + 'static {
   |                          ---------- required by this bound in `World`
```

I used to have an mqtt client connected between steps. Perhaps I am using `World` wrong, should I just keep simple data and reconnect every step?

**Comment by bbqsrc** [comment] 2021-01-07 16:34
This is definitely a painpoint. Something you could do instead of putting it into the world is make it a (please don't shoot me) a global mutable static behind a RwLock, if the same instance is used amongst them all. In general we'd want it such that you produce a new connection to be used per scenario, so that nothing breaks, but with the current "World" model, that doesn't work in all cases, particularly where interior mutability is concerned.

This is a space that requires a bit more thought.

**Comment by jonasrichard** [comment] 2021-01-12 15:49
That is a pitty. Ran into the same issue. Personally, if I need to choose, I would rather to prefer the acceptance test panic if my code panic then catching the panics, and all data should be UnwindSafe in World. If I use a global variable, the whole World concept stops making sense.

**Comment by bbqsrc** [comment] 2021-01-12 15:58
I suppose I should make clear I was not suggesting that the global variable solution was a _good_ solution, just one of the only workarounds I could think of for that moment. I would note that cucumber-rust is 0.7 for good reason, and that reason is simple: unproven API, limited documentation and limited usage at-large yet. 😄

it may simply be that we stumble upon a very simple pattern for handling UnwindSafe requirements that keeps the testing safe and accurate while also carrying the correct panic information so the issue is debuggable.

I appreciate your frustrations, I really do. All I can suggest right now however is having a poke around at the code and see what we can come up with that makes this work in more cases by default, or assisting by providing documented examples on how to work around these edge cases. I'm always happy to help new contributors. 🙂

**Comment by bbqsrc** [comment] 2021-01-12 16:05
Haha, well, @bgrosse-midokura, I removed the requirement for UnwindSafe from the trait in the `main` branch and all tests passed. Try it out?

**Comment by bgrosse-midokura** [comment] 2021-01-15 18:24
@bbqsrc sorry for not replying, I changed my tests meanwhile to run without cucumber-rust. But I will try again, and report back here!

**Comment by bbqsrc** [comment] 2021-01-18 11:36
I will close this issue for now. @bgrosse-midokura, if you do end up doing what you said, feel free to reply here and I'll reopen if there's still issues.

**Closed by bbqsrc** 2021-01-18 11:36 UTC
Labels: documentation, help wanted
