### ISSUE TITLE
it' s not work properly on clion test

### ISSUE THREAD

**Issue by qx** [bbqsrc/cucumber-rust#121] opened 2021-06-08 00:59 UTC
```
Testing started at 08:59 ...
/Users/ok/github/cucumber-rust-example/target/debug/deps/cucumber-0a00e8bfd21a9e71 --format=json -Z unstable-options --show-output
error: Found argument '--format' which wasn't expected, or isn't valid in this context

USAGE:
    cucumber-0a00e8bfd21a9e71 [FLAGS] [OPTIONS]

For more information try --help

Process finished with exit code 1
```

**Comment by VexedPanda** [comment] 2021-07-06 18:05
Note that you can avoid the error by removing .cli() from your Cucumber builder call.

However, it still doesn't cause outputs that clion can parse, so there's no success/fail entries in the test result tree, and a failure (even with returning 1) is still considered all tests passing by clion.

I'd really like to see cucumber-rust honor the json format request and output results in a way that matches libtest and clion parses natively.

**Comment by VexedPanda** [comment] 2021-07-06 21:13
This may be the same as https://github.com/bbqsrc/cucumber-rust/issues/50

**Comment by bbqsrc** [comment] 2021-07-19 14:09
Dupe of #50 most likely.

**Closed by bbqsrc** 2021-07-19 14:09 UTC
